sudo: false
language: node_js
node_js:
  - '4'
  - '6'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
